# ---------------------------
# nextcloud-resources.yaml
# ---------------------------

# StorageClass für Nextcloud
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-ssd-nextcloud
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
# PersistentVolume für Nextcloud
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
  labels:
    app: nextcloud
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ssd-nextcloud
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /var/openebs/nextcloud
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker1

---
# PersistentVolumeClaim für Nextcloud
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ssd-nextcloud
  resources:
    requests:
      storage: 300Gi
  selector:
    matchLabels:
      app: nextcloud

---
# Redis Deployment (für Nextcloud-Cache)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2
          command: ["redis-server", "--appendonly", "yes"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}

---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379

---
# Nextcloud Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker1
      containers:
        - name: nextcloud
          image: nextcloud:latest
          env:
            - name: MYSQL_HOST
              value: mariadb
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mysql-database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mysql-password
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-pvc

---
# Nextcloud Service
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
    - port: 80
      targetPort: 80

---
# Nextcloud CronJob
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: nextcloud-cron
              image: nextcloud:latest
              command: ["php", "/var/www/html/occ", "background:cron"]
              env:
                - name: MYSQL_HOST
                  value: mariadb
                - name: MYSQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: mariadb-secret
                      key: mysql-database
                - name: MYSQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: mariadb-secret
                      key: mysql-user
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mariadb-secret
                      key: mysql-password
              volumeMounts:
                - name: nextcloud-data
                  mountPath: /var/www/html
          restartPolicy: OnFailure
          volumes:
            - name: nextcloud-data
              persistentVolumeClaim:
                claimName: nextcloud-pvc

---
# Ingress für Nextcloud
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: nextcloud.druckruck.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud
                port:
                  number: 80
