# ---------------------------
# nextcloud.yaml - Stabilisierte Version
# ---------------------------

# StorageClass für Nextcloud
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-ssd-nextcloud
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
# PersistentVolume für Nextcloud
# PVs sind cluster-weit, daher kein Namespace hier nötig
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
  labels:
    app: nextcloud
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ssd-nextcloud
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /var/openebs/nextcloud
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker1

---
# PersistentVolumeClaim für Nextcloud
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  namespace: nextcloud  # <--- WICHTIG: Erzwingt den korrekten Namespace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ssd-nextcloud
  resources:
    requests:
      storage: 300Gi
  # Selector entfernt für sauberes Binding

---
# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2
          command: ["redis-server", "--appendonly", "yes"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}

---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: nextcloud
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379

---
# Nextcloud Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      # Stellt sicher, dass der Pod auf dem gleichen Node wie das PV landet
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker1
      containers:
        - name: nextcloud
          image: nextcloud:latest
          env:
            - name: MYSQL_HOST
              value: mariadb
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mysql-database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mysql-password
            - name: REDIS_HOST
              value: redis
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-pvc

---
# Nextcloud Service
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
    - port: 80
      targetPort: 80

