# postgres-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hedgedoc-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path   # <-- wichtig für K3s
  resources:
    requests:
      storage: 1Gi
