# postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hedgedoc-postgres
spec:
  selector:
    app: hedgedoc-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
