apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: ">=6.0.0"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: nextcloud

  values:

    nodeSelector:
      kubernetes.io/hostname: worker1

    ingress:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
      hosts:
        - host: nextcloud.druckruck.de
          paths:
            - path: /
              pathType: Prefix

    nextcloud:
      image:
        repository: nextcloud
        tag: 33.0.0-apache

      host: nextcloud.druckruck.de

      username: admin
      password: "Schanzenschiss1873402!"

      extraEnv:
        - name: MYSQL_HOST
          value: nextcloud-mariadb
        - name: MYSQL_DATABASE
          value: nextcloud
        - name: MYSQL_USER
          value: nextcloud
        - name: MYSQL_PASSWORD
          value: "Schanzenschiss1873402!"
        - name: PHP_EXTENSIONS
          value: mbstring,intl,bcmath

    persistence:
      enabled: true
      storageClass: openebs-hostpath
      size: 100Gi

    mariadb:
      enabled: true

      image:
        repository: mariadb
        tag: "10.11"

      auth:
        database: nextcloud
        username: nextcloud
        password: "Schanzenschiss1873402!"
        rootPassword: "Schanzenschiss1873402!"

      primary:
        nodeSelector:
          kubernetes.io/hostname: worker1

        persistence:
          enabled: true
          storageClass: openebs-hostpath
          size: 20Gi

        podSecurityContext:
          fsGroup: 1001

        containerSecurityContext:
          runAsUser: 1001

      volumePermissions:
        enabled: true
