---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: projects
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./projects
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
