k# ---------------------------
# mariadb.yaml - Stabilisierte Version
# ---------------------------

# StorageClass für MariaDB
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-ssd-mariadb
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
# PersistentVolume für MariaDB (Cluster-weit)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  labels:
    app: mariadb
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ssd-mariadb
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /var/openebs/mariadb
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker1

---
# StatefulSet für MariaDB
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: nextcloud # <--- SICHERHEITS-KORREKTUR: Expliziter Namespace
spec:
  serviceName: mariadb
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker1
      containers:
        - name: mariadb
          image: mariadb:10.11
          env:
            # WICHTIG: Diese Secrets müssen existieren, sonst startet der Pod nicht.
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mysql-database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mysql-password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mariadb-data
        # KEIN expliziter Namespace hier, da er vom StatefulSet/Metadata geerbt wird.
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-ssd-mariadb
        resources:
          requests:
            storage: 20Gi

---
# Service für MariaDB
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: nextcloud # <--- SICHERHEITS-KORREKTUR: Expliziter Namespace
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
